### ISSUE TITLE
Checkbox Field Appears with MatFormField Input Appearance

### ISSUE THREAD

**Issue by EvanScott542** [ngx-formly/ngx-formly#3727] opened 2023-06-30 14:10 UTC
**Description**
Appearance of `mat-form-field`, either underline by default or outline, displays around checkbox. Only the checkbox and its label should show. 

**Minimal Reproduction**
This can be seen in the provided starter template. There should be no outline surrounding the checkbox field. 
- Material: https://stackblitz.com/edit/ngx-formly-ui-material

**Your Environment**

- Angular version: 16.0.0
- Formly version: 6.1.4

**Comment by aitboudad** [comment] 2023-09-16 20:03
Duplicate of #3558

**Closed by aitboudad** 2023-09-16 20:03 UTC
Labels: bug
