### ISSUE TITLE
@ngx-formly/ionic incompatible with @ionic/angular 8.3.0

### ISSUE THREAD

**Issue by KeyTurns** [ngx-formly/ngx-formly#3987] opened 2024-09-15 09:02 UTC
Description: The @ngx-formly/ionic version 6.3.7 is not compatible with the latest version of @ionic/angular (8.3.0). The following error occurs when trying to use the library:

`./node_modules/@ngx-formly/ionic/fesm2020/ngx-formly-ionic-radio.mjs:95:259-280 - Error: export 'RadioValueAccessor' (imported as 'i1') was not found in '@ionic/angular' (possible exports: ActionSheetController, AlertController, AngularDelegate, AnimationController, BooleanValueAccessor, Config, DomController, GestureController, ION_MAX_VALIDATOR, ION_MIN_VALIDATOR, IonAccordion, IonAccordionGroup, IonActionSheet, IonAlert, IonApp, IonAvatar, IonBackButton, IonBackdrop, IonBadge, IonBreadcrumb, IonBreadcrumbs, IonButton, IonButtons, IonCard, IonCardContent, IonCardHeader, IonCardSubtitle, IonCardTitle, IonCheckbox, IonChip, IonCol, IonContent, IonDatetime, IonDatetimeButton, IonFab, IonFabButton, IonFabList, IonFooter, IonGrid, IonHeader, IonIcon, IonImg, IonInfiniteScroll, IonInfiniteScrollContent, IonInput, IonInputPasswordToggle, IonItem, IonItemDivider, IonItemGroup, IonItemOption, IonItemOptions, IonItemSliding, IonLabel, IonList, IonListHeader, IonLoading, IonMaxValidator, IonMenu, IonMenuButton, IonMenuToggle, IonMinValidator, IonModal, IonNav, IonNavLink, IonNote, IonPicker, IonPickerColumn, IonPickerColumnOption, IonPickerLegacy, IonPopover, IonProgressBar, IonRadio, IonRadioGroup, IonRange, IonRefresher, IonRefresherContent, IonReorder, IonReorderGroup, IonRippleEffect, IonRouterOutlet, IonRow, IonSearchbar, IonSegment, IonSegmentButton, IonSelect, IonSelectOption, IonSkeletonText, IonSpinner, IonSplitPane, IonTab, IonTabBar, IonTabButton, IonTabs, IonText, IonTextarea, IonThumbnail, IonTitle, IonToast, IonToggle, IonToolbar, IonicModule, IonicRouteStrategy, IonicSafeString, IonicSlides, LoadingController, MenuController, ModalController, NavController, NavParams, NumericValueAccessor, PickerController, Platform, PopoverController, RouterLinkDelegate, RouterLinkWithHrefDelegate, SelectValueAccessor, TextValueAccessor, ToastController, createAnimation, createGesture, getIonPageElement, getPlatforms, getTimeGivenProgression, iosTransitionAnimation, isPlatform, mdTransitionAnimation, openURL)
`

Steps to Reproduce:
Install @ngx-formly/ionic version 6.3.7 and @ionic/angular version 8.3.0.
Run the application.

**Your Environment**

- Angular version: 18.2.3
- Formly version: 6.3.7
- ionic/angular: 8.3.0,

**Comment by aitboudad** [comment] 2024-10-12 20:16
Duplicate of #3902

**Closed by aitboudad** 2024-10-12 20:16 UTC
Labels: bug
