### ISSUE TITLE
JSON Powered Formly form - conditionally disabling form fields without expressionProperties

### ISSUE THREAD

**Issue by timh770773** [ngx-formly/ngx-formly#3361] opened 2022-06-27 14:30 UTC
Hi there, I have a fairly complex Formly form that's generated via JSON. There are several fields that need to conditionally be disabled (or required) depending on formState. Previously I was using `expressionProperties` to do this and that was working great, however, once the code was pushed to upper environments I was getting CSP errors:

_EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:_

I didn't want to change the security settings on the servers for this and after giving it some thought I decided to avoid `expressionProperties` altogether.

I was able to move the conditional logic from the JSON to my custom Formly components and that worked perfectly. However, for the native HTML elements like textareas, I'm having some trouble figuring out a good way to go about this... there is no custom component where I can add the conditional in an `ngOnInit` for example.

The only way I can think of to do this is to map the whole form object, filtering for the native elements, and running the conditional on the individual controls. The problem there is that these native elements are nested in a fairly large object at varying levels, inside of various form groups/form arrays. Parsing for the specific controls would be a nightmare and probably not great performance-wise.

So my question is, is there another way to do this aside from `expressionProperties`? The only other thing I can think of is using vanilla JS to query for the elements and disable them, but I'd like to stay within Angular if possible. Thanks.

**Comment by kenisteward** [comment] 2022-06-27 19:05
What version are you using?

Scanning through the code we don't use eval. We use instantiated functions
to evaluate the functions so I'm not sure why you'd get that error.

If you are using eval in your formstate functions that definitely shouldn't
be happening.

I've done this same thing with an internal library using default formly
configurations as well.

**Comment by timh770773** [comment] 2022-06-27 19:30
Weird, yeah I don't see any instances of `eval` in node_modules/@ngx-formly for the package we currently have installed.

I get the error if there are any `expressionProperties` in the JSON, if all I do is remove them, the error no longer gets thrown in the console.

Maybe there's something wrong with how I'm using `expressionProperties`? 

Here's an example from my JSON in case it's helpful:
```
"expressionProperties": {
  "templateOptions.disabled": "formState.disabled",
  "templateOptions.required": "field.parent?.key > 0 ? false : true"
}
```

**Comment by kenisteward** [comment] 2022-06-27 19:32
Yup that's what we were using until just recently.

Either way,  something else you can do is setup an oninit ( either in an
extension or field directly ) to derive disabled from a formstate.

**Comment by timh770773** [comment] 2022-06-28 14:34
I'm pretty sure it's the

`(Function.appy(void 0, __spread(argNames, ["return " + expression + ";"])))`

that's causing the `unsafe-eval` to be thrown... dynamically inserting the expression gets treated as `eval`-like logic by the CSP

**Comment by aitboudad** [comment] 2022-07-01 21:40
Duplicate of #2537, you may try to use a custom extension which convert a string expression to function without using `Function.apply` also PR welcomed!

**Closed by aitboudad** 2022-07-01 21:40 UTC
Labels: question

**Comment by kenisteward** [comment] 2022-10-11 07:54
You can extend it to the fields that don't have components by defining an
extension instead. If you can setup a stackbliz of something that you have
I'll try to update it with what I mean.

It seems I misunderstood the CSP and that is correct. Using function() is
what we do so with your CSP it won't work.

**Comment by danbilokha** [comment] 2022-12-15 09:56
I fixed it my using `hideExpression`. 

`hideExpression: !model.showCoApplicantForm` I was getting unsafe eval error too, which is make sense and indeed caused by Function @timh770773 mentioned. 

`hideExpression: (model: any) => !model.showCoApplicantForm,` works without issues
