### ISSUE TITLE
add support of standalone components in angular 16

### ISSUE THREAD

**Issue by angularui06** [ngx-formly/ngx-formly#3721] opened 2023-06-21 14:39 UTC
**Angular Version: 16.0.4 Formly Version: 6.1.7

I just changed my Angular project to standalone components, which deleted all of the modules. We developed custom formly components, such as input fields and dropdown menus, with the following configuration:**

`@NgModule({
  FormlyModule.forRoot({
      types: [
        {
          name: 'input',
          component: CustomInputComponent,
          wrappers: ['test-wrapper'],
        }
      ],
      validators: [
        {
          name: 'mandatory',
          validation: CustomMandatoryValidator,
        },
      ],
      wrappers: [
        {
          name: 'test-wrapper',
          component: TestWrapperComponent,
        },
      ],
    })
  })`

It's generating an issue when I try to relocate this configuration inside the standalone components imports section. 
**Error: Type 'ModuleWithProviders' is not assignable to type 'readonly any[] | Type'**, How to fix this issue?

**Comment by Dyqmin** [comment] 2023-06-22 10:29
Correct, you can't import a module with providers inside of a standalone component. Instead, try to set your formly configuration with `importProvidersFrom` which will extract all of your providers from the module you provided.

```ts
importProvidersFrom([
  FormlyModule.forRoot({
    types: [
      {
        name: 'input',
        component: CustomInputComponent,
        wrappers: ['test-wrapper'],
      },
    ],
    validators: [{ name: 'mandatory', validation: CustomMandatoryValidator }],
    wrappers: [{ name: 'test-wrapper', component: TestWrapperComponent }],
  }),
])
```

Notice that `importProvidersFrom` returns `EnvironmentProviders`, so you should provide it in application/environment injector level.

If you are using different configurations for specific parts of your application, you can create a helper function for that.

```ts
export const provideFormlyConfig = (config: ConfigOption): EnvironmentProviders => importProvidersFrom([
  FormlyModule.forChild(config),
]);
```

And use it like so
```ts
const routes = [
  {
    path: 'foo',
    component: FooComponent,
    providers: [
      provideFormlyConfig({ 
        ... 
      })
    ]
  },
] as Route[]
```

**Comment by angularui06** [comment] 2023-06-24 03:35
Thanks for responding, I will check.

**Comment by aitboudad** [comment] 2024-06-09 13:22
Duplicate of #3811

**Closed by aitboudad** 2024-06-09 13:22 UTC
Labels: enhancement
