### ISSUE TITLE
Options at formlygroup cant access or update the data from API

### ISSUE THREAD

**Issue by stefani0** [ngx-formly/ngx-formly#2500] opened 2020-09-16 08:37 UTC
Im passing data from a API call to a select list with formly. when i try to implement wth a mockup its working but when call API data are not displayed despite the select is droped down.
`
 {        key: 'attributeName',
          type: 'custom-select',
          templateOptions: {
            
            placeholder: 'Enter value',
            // required: true,
            options: this.variableName,
            //  [       with mockup work
            //   { title: 'Snickers', value: 'snickers' },
            //   { title: 'Baby Ruth', value: 'baby_ruth' },
            //   { title: 'Milky Way', value: 'milky_way' },
            //   { title: 'Baby Ruth', value: 'baby_ruth' },
            //   { title: 'Milky Way', value: 'milky_way' },
            //   ],
            value: "name",

            onChangeFilter: (filter) => {
              console.log("onChangeFilter", filter)
              const termStr = new String(filter);
              if (termStr.length >= 3) {
              this.variableName = this.searchForData(termStr)           
              }
            },
          },       
        },`

the service is below and data are coming with sucess

`  searchForData(term) { 
   this.ruleService.searchTermsAutocomplete(term).subscribe(
      (result) => {
        this.variableName = result.data;  
        return  this.variableName
      }
    )
  }`

**Comment by Thiru0808** [comment] 2020-09-18 04:22
Use expressionProperties to set templateOptions.options

https://github.com/ngx-formly/ngx-formly/issues/2497

**Comment by aitboudad** [comment] 2020-09-26 17:25
duplicate of #2503 also I may need a proper reproduction example.

**Closed by aitboudad** 2020-09-26 17:25 UTC
Labels: question
