### ISSUE TITLE
Create Online Playground to quickly prototype and test forms

### ISSUE THREAD

**Issue by classifieds-dev** [ngx-formly/ngx-formly#2230] opened 2020-05-07 19:42 UTC
Hello,

I was wondering if there is any interest in creating an online playground similar to this.

https://hamidihamza.com/ajsf/

I've known about that json forms package for a long time and have just recently discovered formly which looks amazing. Anyway it would be really nice if forms could tested quickly online like that project provides but with formly.

I've been using that the last few days to quickly test generated form schemas from NJSONSchema and it is considerably more efficient than modifying my app code every time.

**Comment by aitboudad** [comment] 2020-05-07 21:32
I've done an initial work, I'll try to launch it once time allows.

For Json-schema you may check https://json-editor.github.io/json-editor/

**Comment by aitboudad** [comment] 2020-05-09 02:55
duplicate of #1524

**Closed by aitboudad** 2020-05-09 02:55 UTC
Labels: enhancement
