### ISSUE TITLE
Add Support for Angular 11.1+

### ISSUE THREAD

**Issue by mattpenner** [ngx-formly/ngx-formly#2701] opened 2021-02-13 03:52 UTC
**Description**
The ng add @ngx-formly/schematics command no longer works. It now throws the error:
`An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'`

**Minimal Reproduction**

1. Use Angular 11.1 or higher. 
2. Create a new project
3. Run ng add @ngx-formly/schematics

- Angular version: 11.1.4
- Formly version: 5.10.13

**Additional context**
As of Angular CLI 11.1 they have removed schematics/angular/utility/config.

**Comment by aitboudad** [comment] 2021-02-13 08:59
This issue has been fixed and released as part of [v5.5.14](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.14) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by mburger81** [comment] 2021-02-14 05:23
@aitboudad do you intend v5.**10**.15 and not v5.**5**.14

We are still running into this issue, there is no verbose output
```
Skipping installation: Package already installed
Cannot read property 'kind' of undefined
```


```
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.3
typescript                      4.0.7
```

**Comment by aitboudad** [comment] 2021-02-14 16:39
@mburger81 the version is `v5.10.14`, tested with `11.1.4` and `11.2.0` without getting any issues :thinking:.

**Comment by AshMcConnell** [comment] 2021-02-15 13:37
I'm getting the `Cannot read property 'kind' of undefined on Angular 10 too

`@angular-devkit/architect          0.1001.6
@angular-devkit/build-angular      0.1001.6
@angular-devkit/core               10.1.6
@angular-devkit/schematics         10.1.6
@angular/cdk                       10.2.4
@angular/cli                       10.1.6
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.4
@angular/material-moment-adapter   10.2.4
@schematics/angular                10.1.6
@schematics/update                 0.1001.6
rxjs                               6.6.3
typescript                         4.0.3`

**Comment by mattpenner** [comment] 2021-02-15 23:01
Confirmed this has fixed what I originally posted.  I have been able to successfully install ngx-formly now on Angular 11.1.4 with the following command:
`ng add @ngx-formly/schematics --ui-theme=primeng`

**Comment by vitale232** [comment] 2021-03-16 18:30
Is this issue still considered closed?

I'm having "`Cannot read property 'kind' of undefined`" issues with the `ng add` command. FWIW, I'm working in an `nx` workspace on Windows 10 - WSL2 running Ubuntu 20.04

```shell
$ nx add @ngx-formly/schematics --ui-theme=material
ℹ Using package manager: npm
✔ Found compatible package version: @ngx-formly/schematics@5.10.14.
✔ Package information loaded.
✔ Package successfully installed.
Cannot read property 'kind' of undefined
```
Only `@ngx-formly/schematics` was added to my `package.json`. Manually installing `@ngx-formly/core` and `@ngx-formly/material` got me going.

Here are my dependencies:
```json
{
    "dependencies": {
        "@angular/animations": "11.2.3",
        "@angular/cdk": "11.1.1",
        "@angular/common": "11.2.3",
        "@angular/compiler": "11.2.3",
        "@angular/core": "11.2.3",
        "@angular/forms": "11.2.3",
        "@angular/material": "11.1.1",
        "@angular/platform-browser": "11.2.3",
        "@angular/platform-browser-dynamic": "11.2.3",
        "@angular/router": "11.2.3",
        "@ngrx/component": "^11.0.1",
        "@ngrx/component-store": "11.0.0",
        "@nrwl/angular": "11.4.0",
        "@vhb/vhb-map": "^2.1.1",
        "@vhb/vhb-pdf": "^0.1.2",
        "ag-grid-angular": "^25.1.0",
        "ag-grid-community": "^25.1.0",
        "angular-split": "^5.0.0",
        "lodash": "^4.17.21",
        "rxjs": "^6.6.6",
        "tslib": "^2.0.0",
        "zone.js": "^0.10.2"
    }
}
```

**Comment by kgathi2** [comment] 2021-03-16 19:59
Getting the same issue with Angular 11.2.4 using yarn
```sh
ng add @ngx-formly/schematics --ui-theme=bootstrap
ℹ Using package manager: yarn
✔ Found compatible package version: @ngx-formly/schematics@5.10.14.
✔ Package information loaded.
✔ Package successfully installed.
Cannot read property 'kind' of undefined
```

my depenencies
```json
 "dependencies": {
    "@angular/animations": "~11.2.4",
    "@angular/common": "~11.2.4",
    "@angular/compiler": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/forms": "~11.2.4",
    "@angular/localize": "~11.2.4",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "@ng-bootstrap/ng-bootstrap": "^9.0.2",
    "@ng-select/ng-select": "^6.1.0",
    "@ngx-formly/schematics": "5.10.14",
    "@ngxs/form-plugin": "^3.7.1",
    "@ngxs/logger-plugin": "^3.7.1",
    "@ngxs/router-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",
    "bootstrap": "^4.5.0",
    "rxjs": "~6.6.6",
    "ts-json-api": "^1.1.0",
    "ts-toolbelt": "^8.0.7",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  }
```

**Comment by aitboudad** [comment] 2021-03-16 20:46
I think it occurs only on Windows as I can't reproduce it from my side

**Comment by aitboudad** [comment] 2021-03-16 21:01
Could you please try the following version `5.10.0-dev.6125bfe1` and let me know if that fixes the issue from your side.


- Angular CLI

```bash
ng add @ngx-formly/schematics@5.10.0-dev.6125bfe1 --ui-theme=bootstrap
```

- NX
```bash
nx add @ngx-formly/schematics@5.10.0-dev.6125bfe1 --ui-theme=material
```

**Comment by vitale232** [comment] 2021-03-16 21:14
That's always fun...

I'm still getting the same error:

```shell
$ nx add @ngx-formly/schematics@5.10.0-dev.6125bfe1 --ui-theme=material
ℹ Using package manager: npm
✔ Package information loaded.
✔ Package successfully installed.
Cannot read property 'kind' of undefined
```

Let me know if I can provide any other info to help.

**Comment by aitboudad** [comment] 2021-03-16 21:15
Note: updated the version to `5.10.0-dev.ffc0c1c6`

@vitale232 check with `5.10.0-dev.ffc0c1c6` instead.

**Comment by aitboudad** [comment] 2021-03-16 21:30
in case it doesn't work do no waste your time and use npm install instead:

- Step 1: `npm install`:

```bash
npm install @ngx-formly/core @ngx-formly/material
````

- Step 2: Import `FormlyModule`:

```patch
import { AppComponent } from './app.component';
+ import { ReactiveFormsModule } from '@angular/forms';
+ import { FormlyModule } from '@ngx-formly/core';
+ import { FormlyMaterialModule } from '@ngx-formly/material';

@NgModule({
  imports: [
    BrowserModule
+   ReactiveFormsModule,
+   FormlyModule.forRoot(),
+   FormlyMaterialModule,
  ],
  ...
})
export class AppModule { }
```

**Comment by vitale232** [comment] 2021-03-16 21:33
@aitboudad That build fixes it for me. The schematic added `@ngx/formly @ngx-formly/material`, imported the modules in my default project, and included the `{ extras: { lazyRender: true } }` config in the `forRoot` call.

Thanks for all that you do.

**Comment by aitboudad** [comment] 2021-03-16 21:48
Awesome, just pushed a stable release `5.10.15` which you could use instead (no need to specify the version).

```bach
ng add @ngx-formly/schematics --ui-theme=bootstrap
```

**Comment by kgathi2** [comment] 2021-03-17 14:40
Looks good now, but when i run, the schematics are added to the dependencies as opposed to the devDependencies. Should this be the case?

**Comment by aitboudad** [comment] 2021-03-18 12:45
@kgathi2 yes I think it makes sense to move it into the devDependencies, I'll fix that in the next release

**Comment by tanjunior** [comment] 2021-09-02 07:47
Angular12
"SchematicsNgxFormlyShell" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Cannot read property 'kind' of undefined

**Comment by aitboudad** [comment] 2021-09-21 14:08
could you please check if the issue occurs on https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.1

**Comment by OriolInvernonLlaneza** [comment] 2021-09-21 14:14
It works but installs the schematics as dependencies and gets version ^5.0.0 of @ngx-formly/core and @ngx-formly/primeng.

**Closed** 2021-11-25 21:51 UTC
Labels: bug
