### ISSUE TITLE
"display: none" is not set when lazyRender is true

### ISSUE THREAD

**Issue by yinglejia** [ngx-formly/ngx-formly#3312] opened 2022-05-27 04:22 UTC
**Description**

We set `lazyRender` to `true` in our app and use `hideExpression` to conditionally hide some fields.

The problem we have is that even though the hidden fields are not rendered, the formly wrappers `<formly-field>` are still rendered and they do not have `display: none`. Therefore, they are still part of the visual tree and can break form layout.

- When `lazyRender` is `false`, Formly adds `display: none` to `<formly-field>`. https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.field.ts#L210
- When `lazyRender` is `true`, Formly does not add `display: none`. It seems it should?

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 12.2.15
- Formly version: 5.12.0

**Additional context**

**Comment by aitboudad** [comment] 2022-05-27 16:11
Duplicate of #3313

**Closed by aitboudad** 2022-05-27 16:11 UTC
Labels: bug
