### ISSUE TITLE
formly & JSON Schema Validation

### ISSUE THREAD

**Issue by petros-greece** [ngx-formly/ngx-formly#2433] opened 2020-08-06 18:53 UTC
**Description**

1. I build a website that renders dynamic forms with the combination of formly and json schema.
When my json schema has a field of type number and also mimimum maximum and multipleOf attributes, the input field renders correctly, but something goes wrong with the validation if the multipleOf is a float point number.

"float": {
  "type": "number",
  "title": "A float number",
  "minimum": 3,
  "maximum": 10,
  "multipleOf" : 0.1
},   

2. Another validation problem is that when I declare an integer on my schema if the user enters a float point number is considered valid by the form, and it shouldn't be valid.

**Comment by aitboudad** [comment] 2020-08-29 13:02
1. fixed by #2441

2. duplicate of #2360

**Closed by aitboudad** 2020-08-29 13:02 UTC
Labels: bug
