### ISSUE TITLE
When can we access ionic(7) support the latest version of ngx-formly ?

### ISSUE THREAD

**Issue by serkaneken** [ngx-formly/ngx-formly#3717] opened 2023-06-16 14:42 UTC
Hello, 

I already opened this issue( https://github.com/ngx-formly/ngx-formly/issues/3682 ) for support/request.
Could I learn when can we access the support of ionic 7 for ngx-formly ? 
Is there specific work on upgrades ngx-formly ? Actually we are wondering about the estimated date.

Thank you in advance.

**Comment by FBosito** [comment] 2023-06-26 05:39
Hi, 

also would be interested in this.

Thx
Günter

**Comment by prajput1994** [comment] 2023-08-22 06:43
Hi,

We are also using @ng/formly and having issue with ionic 7 update. Is there any update for when this issue will resolve for ionic 7.

Thanks

**Comment by mhasansheikdawood** [comment] 2023-08-22 09:07
Looking forward for the ionic7 support.

Can someone help us with the expected date for the support!!

**Comment by msyler** [comment] 2023-09-15 20:49
Having exact same issue, Thanks!

**Comment by aitboudad** [comment] 2023-09-16 19:59
Duplicate of #3643

**Closed by aitboudad** 2023-09-16 19:59 UTC
Labels: question
