### ISSUE TITLE
How to set an id for "mat-option"?

### ISSUE THREAD

**Issue by vivaworld** [ngx-formly/ngx-formly#3484] opened 2022-11-03 17:11 UTC
**Question**

I want to set the id of "mat-option" tags so that they are fixed for testing purposes.

right now "mat-option" gets random numbers in different environments with different builds. Ex:
"mat-option-677", "mat-option-201" and so on. 

please note that it is not always "mat-option-0", "mat-option-1" and ....

The "id" given will be used only for "mat-select" as shown in the image below, but is there a way to assign an "id" also for "mat-option"?

![image](https://user-images.githubusercontent.com/114763996/199788149-5d203b44-0744-4d43-a41a-b3351edbc802.png)

https://stackblitz.com/edit/ngx-formly-ui-material-ka5p7a?file=src/app/app.component.ts

**Comment by aitboudad** [comment] 2022-11-06 18:31
Duplicate of #3484.

Not supported yet, you'll need to override the select type instead, also PR welcomed!

**Closed by aitboudad** 2022-11-06 18:31 UTC
Labels: question

**Comment by aitboudad** [comment] 2022-11-13 12:32
> Could you please provide an example or point me in the right direction on how to override the select type?

- https://formly.dev/docs/guide/custom-formly-field
- https://github.com/ngx-formly/ngx-formly/tree/main/src/ui/material/select/src
