### ISSUE TITLE
Formly not compatibel with latest IONIC

### ISSUE THREAD

**Issue by QICON-Gustav** [ngx-formly/ngx-formly#3644] opened 2023-04-11 19:43 UTC
**Description**
When updating to latest IONIC with latest Formly a warning arises, i have not found any way around this. Same problem arises even though i create a custom InputFieldType: 

Ionic Warning]: ion-input now requires providing a label with either the "label" property or the "aria-label" attribute. To migrate, remove any usage of "ion-label" and pass the label text to either the "label" property or the "aria-label" attribute.

Example: <ion-input label="Email"></ion-input>
Example with aria-label: <ion-input aria-label="Email"></ion-input>

For inputs that do not render the label immediately next to the input, developers may continue to use "ion-label" but must manually associate the label with the input by using "aria-labelledby".

Developers can use the "legacy" property to continue using the legacy form markup. This property will be removed in an upcoming major release of Ionic where this form control will use the modern form markup..

**Minimal Reproduction**
https://stackblitz.com/edit/angular-kqgkjz?file=src/app/app.component.ts

**Your Environment**

- Angular version: 15.2.6
- Formly version: 6.1.3

**Comment by aitboudad** [comment] 2023-05-06 16:01
Duplicate of #3643

**Closed by aitboudad** 2023-05-06 16:01 UTC
Labels: bug
