### ISSUE TITLE
Callback after the form is ready

### ISSUE THREAD

**Issue by SathyaramSoni** [ngx-formly/ngx-formly#2279] opened 2020-05-26 07:50 UTC
Hi,

Is there a callback feature to know when the form is ready. Need to add a logic when all the fields are ready/intilized.

I know lifecycle hooks on fields is an option. But, that won't work since the field config are returned from backend in my application. We make a REST api call to get the formlyconfig.

Regards

**Comment by aitboudad** [comment] 2020-05-27 13:04
duplicate of #1912, for an alternative way, build form manually using `FormlyFormBuilder` service.

```ts
constructor(private builder: FormlyFormBuilder) {}

ngOnInit() {
    ...
    .then(() => {
        this.builder.buildForm(this.form, this.fields, this.model, this.options);
    });
}
```

**Closed by aitboudad** 2020-05-27 13:04 UTC
Labels: question

**Comment by FritzHerbers** [comment] 2020-05-28 11:54
@aitboudad 
Your code snippet confuses me. 

Was the intend to build the form in local variables and hand it over to _formly-form_, who picks them up in onChange? 
In formly-form onChange calls buildForm internally (second time) and finds everything instantiated ?

**Comment by SathyaramSoni** [comment] 2020-07-31 07:21
Is there a way to get notified after formly has completed building the form

something like 

this.builder.buildForm(...). subscribe((a) => {
   // add own logic after form initialized
})

**Comment by aitboudad** [comment] 2020-07-31 17:45
@SathyaramSoni right now `buildForm` is sync so just add your own login after `buildForm` call.
