### ISSUE TITLE
JSON powered (https://ngx-formly.github.io/ngx-formly/examples/other/json-powered) with autocomplete and options observer

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1930] opened 2019-11-14 17:13 UTC
I'm studying using https://ngx-formly.github.io/ngx-formly/examples/other/json-powered
```json
[
  {
    "key": "firstName",
    "type": "input",
    "templateOptions": {
      "label": "First Name"
    }
  },
  {
    "key": "lastName",
    "type": "input",
    "templateOptions": {
      "label": "Last Name"
    }
  },
  {
    "key": "mac",
    "type": "input",
    "templateOptions": {
      "label": "Mac Address",
      "pattern": "([0-9A-F]{2}[:-]){5}([0-9A-F]{2})"
    }
  },
  {
    "key": "color",
    "type": "radio",
    "templateOptions": {
      "label": "Color Preference (try this out)",
      "options": [
        {
          "label": "No Preference",
          "value": null
        },
        {
          "label": "Green",
          "value": "green"
        },
        {
          "label": "Blue",
          "value": "blue"
        }
      ]
    }
  },
  {
    "key": "reason",
    "type": "textarea",
    "templateOptions": {
      "label": "Why?"
    },
    "expressionProperties": {
      "templateOptions.label": "'Why did you choose ' + model.color + '?'"
    },
    "hideExpression": "!model.color"
  }
]
```

But in the example there is no way to use autcomplete and if it will work if it is enclosed in quotes, as a string.
```json
{
      "key": "Autocomplete",
      "type": "autocomplete",
      "templateOptions": {
        "required": true,
        "label": "Autocomplete",
        "placeholder": "Placeholder",
        "appearance": "outline",
        "filter": "(term) => of(this.filterStates('Autocomplete', term))"
      },
    }

```

And to select too, how to include this observable.
```json
{
  "key": "sport",
  "type": "select",
  "templateOptions": {
    "label": "Sport",
    "options": "this.dataService.getSports()",
    "valueProp": "id",
    "labelProp": "name",
  },
}
```

So this is the problem with json powered, using these two components, as mentioned

**Comment by aitboudad** [comment] 2019-11-15 16:58
Duplicate of https://github.com/ngx-formly/ngx-formly/issues/1902#issuecomment-551685489

**Closed by aitboudad** 2019-11-15 16:58 UTC
Labels: question
