### ISSUE TITLE
Change detection in array field does not detect adding element on all levels

### ISSUE THREAD

**Issue by ivanshilo** [ngx-formly/ngx-formly#3352] opened 2022-06-14 17:52 UTC
**Description**
When array gets a new element, change detection happens only on array's level even if change detection callbacks are assigned to its parents as well.

**Minimal Reproduction**
~~https://stackblitz.com/angular/deeomgkqdoa?file=src%2Fapp%2Fapp.module.ts~~
https://stackblitz.com/edit/angular-wma8my?file=src%2Fapp%2Fapp.module.ts

Switch to arrays tab, try to add elements to the inner array - only changes for inner array are detected -> single change detection event.
Try to remove element - changes on every field level are detected -> multiple change events from different levels.

**Comment by ivanshilo** [comment] 2022-06-21 08:48
Sorry, somehow I posted just a default example. This is a correct link
https://stackblitz.com/edit/angular-wma8my?file=src%2Fapp%2Fapp.module.ts

**Comment by aitboudad** [comment] 2022-07-11 19:10
The issue is fixed in `V6` instead, here is a working example: https://stackblitz.com/edit/angular-iqcrty?file=src/app/app.module.ts

**Closed by aitboudad** 2022-07-11 19:10 UTC
Labels: bug
