### ISSUE TITLE
get value from dynamically loaded custom component

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2122] opened 2020-02-29 20:04 UTC
I created a custom type `categories` that dynamically loads some check-boxes, but I couldn't get the form value when it is checked.

https://stackblitz.com/edit/formly-dynamic-component

**Comment by aitboudad** [comment] 2020-03-03 12:45
duplicate of https://github.com/ngx-formly/ngx-formly/issues/2108, one extra note is to control the `formControl` manually use `setValue`:

```ts
onChange(value) {
  this.formControl.setValue(value);
}
```

**Closed by aitboudad** 2020-03-03 12:45 UTC
Labels: question

**Comment by eng-dibo** [comment] 2020-03-03 15:11
I added onChange() but it seems that events are not activated, so onChange() and onClick() didn't work

**Comment by aitboudad** [comment] 2020-03-03 19:45
well, the way you want to render content here is not an Angular way it's a pure javascript:

```ts
document
  .querySelector('your_input_selector')
  .addEventListener("change", () => this. onChange());
```

**Comment by eng-dibo** [comment] 2020-03-28 11:34
what is the body of onChange()?
how to add it's value to the formControl?

**Comment by aitboudad** [comment] 2020-03-30 17:11
> but when I run it from ngOnInit() it shows 0 items.

try with `ngAfterViewInit` instead or use a `setTimeout`.

**Comment by eng-dibo** [comment] 2020-04-01 13:08
I created this [issue](https://stackoverflow.com/questions/60971247/queryselectorall-dosent-work-with-angular-but-works-in-console) so you can understand the problem.

in summary:
`document.querySelectorAll('[name="groups"]').length` from `ngAfterViewInit` gives zero elements,
but if I run the same code from the console it gives 192 items.

**Comment by eng-dibo** [comment] 2020-04-13 20:46
@aitboudad 
now the function onClick() works and receives the element (checkbox input), but I don't know how to add it to the formControl, or get the formControl from the form.

-> temporarily I'm using `setTimeOut`

**Comment by aitboudad** [comment] 2020-04-17 15:25
`formControl` cannot be linked, you'll need to manage those changes manually https://github.com/ngx-formly/ngx-formly/issues/2122#issuecomment-593932620
