### ISSUE TITLE
Manually init the form after data/model is ready

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#1716] opened 2019-08-13 07:23 UTC
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I'm getting 
```
ERROR Error: "Uncaught (in promise): TypeError: this.DataModel is undefined
````

**Expected behavior**
I have one request as the page opens `ngOnInit` which has all the data/model needed by the form, I was able to use it for the model by using 
```
this.model = {...this.model,...dataCollection}
````
However, I can't figure out how to get the select/radio options to populated from the same source which isn't ready yet when the form gets build.

So how can I make the form to wait until all the data is available, or how else I'm supposed to do that?

Thanks for the library

**Please tell us about your environment:** Ionic
* **Angular version:** 8.1
* **Browser:** All
* **Language:** TypeScript 3.4.3
* **Node (for AoT issues):** `node --version` = 10.16.1

**Comment by Et3rnal** [comment] 2019-08-14 08:11
I have changed how I bing the model, now using `model | async` and used `lifecycle` but event with `afterViewInit` the model still empty at the time the lifecycle fires!

There got to be a way other than statically and calling it from API directly? Is there documentation I can look at?

Currently, I have this which does work
`
{
      key: 'selectedPattern',
      type: 'select',
      templateOptions: {
        label: 'Resistance pattern',
        required: true,
        change: (field) => this.selectionChanged(field.formControl.value),
        options: [],
        valueProp: 'value',
        labelProp: 'text'
      },
      expressionProperties: {
        'templateOptions.options': (model) => {
            if(model && model.availablePattern){
              return model.availablePattern;
            }
            return [];
        }        
      }
    }
`
This works, it did fail few times but I didn't look into it as I want to have access to the model before using it which for some reason removing the async pipe and subscribe to the same data source make if fail `Maximum call stack size exceeded` plus its getting called so many times and this might cause issues as I have big forms.

I went back to my old method of loading the model (in the question), wait until its done then let the `formly-form` render and used lifecycle, onInit model to set the the option
`
lifecycle: {
        onInit: (form, field, model) => {
          field.templateOptions.options = model.availablePattern;
        },
      }
`
This works fine however when the page load and after the data loads the page frezes for few seconds until its all ready!

I have about 10 of these in the current form, I have tried using `afterViewInit` instead without improvment

**Comment by aitboudad** [comment] 2019-08-14 13:39
> So how can I make the form to wait until all the data is available, or how else I'm supposed to do that?

keep `fields` empty until the model is ready:
```ts
this.model = {...this.model,...dataCollection};
this.fields = buildFields(this.model);
```
another option is to pass an observable value for options https://stackblitz.com/edit/angular-gwjfs6

**Comment by Et3rnal** [comment] 2019-08-15 04:19
Using the first way inside the subscribe method and after the model is ready and assigned

```
this.model = {...this.model,...dataCollection.soDataCollection}
this.fields = this.buildFormFields(this.model);
```

Didn't change the situation
The second method failed after I used passed the array inside the model!

All this because of one of "select item" as it has so many options, it would be best if not to show the form until it's all rendered and ready,

I tried the hooks on that select but all event fires before its ready. Where else can I hook to know once all done and ready?

BTW, is there a documentation other than the website.

Thanks

**Comment by aitboudad** [comment] 2019-08-15 14:36
could you please provide an example using stackblitz https://stackblitz.com/angular/eppgkvrngqv that illustrate the main issue.
Thanks!

**Comment by Et3rnal** [comment] 2019-08-16 01:59
First of all, I don't think you need to handle this specifically, internally we agreed this is a bad design for a select menu and we look at using something else other than select, maybe async typeahead or so.

Anyway, to replicate you just need a select with ver big list of options (if you have other items they will freeze as well until this one completed)
```
fields: FormlyFieldConfig[] = [
    {
      key: 'Input',
      type: 'select',
      templateOptions: {
        label: 'Input',
        placeholder: 'Placeholder',
        description: 'Description',
        required: true,
        options: [
          {value:'1', label: 'Country1'},
          .
          .
          {value:'700', label: 'Country700'},
`````
https://stackblitz.com/edit/fornly-big-slow-select

In observable its a bit butter, but (a UI feedback would be nice to have)
So, if we a hook or so know when the form is ready so we hide the loader and show the form would be great.

_I just noticed chrome doest seem to have a real issue, firefox and edge do._

Thanks

**Comment by aitboudad** [comment] 2020-05-14 19:00
duplicate of #1912

**Closed by aitboudad** 2020-05-14 19:00 UTC
Labels: enhancement
