### ISSUE TITLE
[FEATURE] Form Creator - Ability to create forms from UI

### ISSUE THREAD

**Issue by vishnu-dev** [ngx-formly/ngx-formly#1835] opened 2019-10-14 11:27 UTC
**I'm submitting a feature request**
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
I don't know of any such feature in this package

**Expected behavior**
Ability to create a json/form from the UI (maybe a drag drop form creator)

**Minimal reproduction of the problem with instructions**
I have seen this in another library called [Surveyjs](https://surveyjs.io)
![Sample UI](https://user-images.githubusercontent.com/21088161/66747984-9ba6f180-eea3-11e9-92b9-b3eb3331fba6.png)

**What is the motivation / use case for changing the behavior?**
Motivation is to make life of the user easier and have more dynamic content in the form

* **Angular version:** 7.X.X

* **Browser:** all

* **Language:** all

**Comment by aitboudad** [comment] 2019-10-14 11:43
it's on our roadmap (probably `v7`), I'm going to close this one since it's duplicate of #1524 and
thanks for the suggestion 👍!

**Closed by aitboudad** 2019-10-14 11:43 UTC
Labels: enhancement

**Comment by vishnu-dev** [comment] 2019-10-14 12:17
Cool. @aitboudad Thanks.
