### ISSUE TITLE
JSON schema form array type Error: this.formControl.removeAt is not a function 

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#1777] opened 2019-09-13 06:20 UTC
[x] bug report
[x] support request

**Current behavior**

After `toFieldConfig(schema)` I get this error `Error: this.formControl.removeAt is not a function ` on validated schema. I don't know why `FormControl` for ArrayField is generated as `FormGroup` and not as `FormArray`

**Expected behavior**

I can remove element from array type without errors, `FormControl` for array type is `FormArray`

**Minimal reproduction of the problem with instructions**

Don't worry about leak of inputs in new elements in example on StackBlitz
arrays in [StackBlitz](https://stackblitz.com/edit/angular-y334nn)
Validated schema => assets > json-schema > arrays.json

**Comment by lkinasiewicz** [comment] 2019-09-13 10:31
Looks like items removal is broken when:
- there is a schema with `items` as an array of schemas
- the array is entirely filled with data from the beginning

**Comment by lkinasiewicz** [comment] 2019-09-13 13:09
This fix is incorrect because some tests fail but it shows where the problem is.

**Closed** 2019-09-16 18:07 UTC
Labels: bug

**Comment by aitboudad** [comment] 2019-09-16 18:36
released in `5.4.2` version.
