### ISSUE TITLE
[docs] update the docs for standalone components

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3832] opened 2023-12-02 14:18 UTC
Angular now uses the standalone components, but the docs here only support the old NgModules.
here is an example, [Presets](https://formly.dev/docs/guide/formly-field-presets)

**Comment by jbruxelle** [comment] 2023-12-06 06:30
Hi @its-dibo, I did it this way, it case it can help you :

```

import { importProvidersFrom } from '@angular/core';
... (other imports)

export const formProviders = importProvidersFrom([
  ReactiveFormsModule,
  FormlyModule.forRoot({
    types: [...TextFieldTypes, CheckboxFieldType],
    validationMessages,
  }),
  FormlyPrimeNGModule,
]);

export const provideForms = () => {
  return formProviders;
};
```

and then in app.config.ts

```
export const appConfig: ApplicationConfig = {
  providers: [
    ...
    provideForms(),
   ...
  ],
};

```

**Comment by aitboudad** [comment] 2023-12-10 11:18
Duplicate of #3721

**Closed by aitboudad** 2023-12-10 11:18 UTC
Labels: bug
