### ISSUE TITLE
how to remove value at runtime between anyof and oneof array

### ISSUE THREAD

**Issue by MonalisaPatnaik** [ngx-formly/ngx-formly#2953] opened 2021-08-18 08:18 UTC
How to remove the Selected value from the anyof collection at runtime?

**https://stackblitz.com/edit/angular-kybqqe-rvdxvz?file=src%2Fassets%2Fjson-schema%2FanyOf.json**

**Comment by aitboudad** [comment] 2021-08-19 21:53
duplicate of #2952

**Closed by aitboudad** 2021-08-19 21:53 UTC
Labels: question
