### ISSUE TITLE
updating IONIC version to v7 for formly/ionic to work with esbuild. 

### ISSUE THREAD

**Issue by siddhant-dev** [ngx-formly/ngx-formly#3934] opened 2024-06-04 07:05 UTC
Formly currently supports ionic v6 and I wanted to know what is the timeline for updating it to ionic v7 

Starting Ionic v7 they have started to support angular v17 and angular latest shinny builder which esbuild and vite, so if formly migrates to ionic v6 then projects using ionic v7 and above can successfully migrate to esbuild.

**Comment by aitboudad** [comment] 2024-06-09 12:05
Duplicate of #3902 #3919

We'll start first on Angular upgrade which is our top priority for now, then next UI IONIC...

**Closed by aitboudad** 2024-06-09 12:05 UTC
Labels: enhancement
