### ISSUE TITLE
v7 timeline

### ISSUE THREAD

**Issue by polferov** [ngx-formly/ngx-formly#3886] opened 2024-03-26 17:39 UTC
[The FAQ section on standalone components support](https://formly.dev/docs/guide/faq/#formly-standalone-components-support) references v7. Is it already possible to predict a timeline for when it will be available?

Best regards!

**Comment by ChristianKlima** [comment] 2024-04-18 06:58
I'm reaching out to inquire about the current status of the formly project. Is development still ongoing, or has it been discontinued?

**Comment by aitboudad** [comment] 2024-04-18 08:09
Hi, currently there is no timeline so its depends on our available time for open source projects.
Once we've got the chance to start working on it we'll let you know also PR is always welcomed!

**Comment by aitboudad** [comment] 2024-06-09 13:00
Duplicate of #3811.

**Update**: The Next week we will start working on Angular 17 support.

**Closed by aitboudad** 2024-06-09 13:00 UTC
Labels: question
