### ISSUE TITLE
Updating model object

### ISSUE THREAD

**Issue by tomav123-git** [ngx-formly/ngx-formly#3603] opened 2023-02-23 13:13 UTC
how can we update the model value. Im doing it in version5 with spread operator.but with v6 im getting model is a read only property error. Sample code with v5 as follows:
this.model= {...this.model, email: 'email'}

- Angular version: 14
- Formly version: 6

**Comment by aitboudad** [comment] 2023-02-23 14:36
Hi,
could you please provide a reproduction, you can use our starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by tomav123-git** [comment] 2023-02-23 15:09
I have added the example in onsubmit function https://stackblitz.com/edit/ngx-formly-ui-bootstrap-4ugz7j?file=src/app/app.component.ts

**Comment by tomav123-git** [comment] 2023-02-24 15:12
@aitboudad i created a similar case, could you pplase check the following fork and help?
https://ngx-formly-ui-bootstrap-wwudsq.stackblitz.io 
[fork](https://ngx-formly-ui-bootstrap-wwudsq.stackblitz.io)

**Comment by tomav123-git** [comment] 2023-02-27 14:07
@aitboudad i'm trying to achieve something like this: https://github.com/ngx-formly/ngx-formly/issues/1116#issuecomment-412297872
Added stackblitz as well, could you please help?

**Comment by aitboudad** [comment] 2023-03-06 18:43
Duplicate of #3607

**Closed by aitboudad** 2023-03-06 18:43 UTC
Labels: bug
