### ISSUE TITLE
Formly does not save previously modified values on add/remove in custom components

### ISSUE THREAD

**Issue by AndrewKoliaka** [ngx-formly/ngx-formly#3549] opened 2023-01-05 15:30 UTC
**Description**
We use a custom FieldArrayType component. After upgrading Formly to v6 adding/removing new items to fieldGroup through methods add/remove causes all previously modified input values not to be saved in a form, but reset to default values.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-koliaka?file=src/app/app.component.ts
1. enter anything or modify any existing value in the input
2. click "Add"
expected result: new input field has been added and all previously modified inputs retain their values
actual result: new input field has been added and all manually edited inputs roll back to their default values

**Your Environment**
- Angular version: 14.1.3
- Formly version: 6.0.4

**Additional context**
My personal observation is that something may be wrong with add/remove methods or I may have missed some configuration flag for this.

**Comment by clark-stevenson** [comment] 2023-01-09 08:31
I had a similar problem on #3527 and had planned to put together a stackblitz in the next couple of weeks as soon as time allows but I feel you have provided a much simpler test which illustrates the issue.  If nothing else, I am glad it's not just me 😅

**Comment by psemerenko** [comment] 2023-01-11 11:26
I have the same issue. Hoping for a solution to be able to upgrade 🥺

**Comment by aitboudad** [comment] 2023-01-11 11:39
It's a regression, you may use the following workaround for now https://github.com/ngx-formly/ngx-formly/issues/3455#issuecomment-1281110976 till a fix is provided!

**Comment by AndrewKoliaka** [comment] 2023-05-04 10:41
Upgraded to the latest version of formly but the bug still persists

**Comment by aitboudad** [comment] 2023-05-06 22:48
Duplicate of #3455

**Closed by aitboudad** 2023-05-06 22:48 UTC
Labels: bug

**Comment by clark-stevenson** [comment] 2023-05-17 16:42
I was unsure how to apply the workaround given it's a fieldArray. 

@AndrewKoliaka  or  @psemerenko do you have any particular ideas or strategies for how you will move ahead alternatively without a fieldArray?  I am upgrading dependencies to Angular 15 (soon 16 on the back of that).  Have any of you used Formly 5 with newer versions of Angular with any success?

**Comment by aitboudad** [comment] 2023-05-17 20:08
@clark-stevenson if time allows, I'll try to provide a fix at the end of this week so you can upgrade to Angular 15 / 16.

**Comment by aitboudad** [comment] 2023-05-20 21:51
This issue has been fixed and released as part of [v6.1.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by clark-stevenson** [comment] 2023-05-23 12:56
Thank you @aitboudad it seems to work perfect again!!  As always, I appreciate it.  👍 💯 🥇
