### ISSUE TITLE
Nativescript: hideExpression on Android, field appears at end of form

### ISSUE THREAD

**Issue by jigsawmegs** [ngx-formly/ngx-formly#3165] opened 2022-02-01 03:09 UTC
**Description**
Issue when using hideExpression on Android devices. Works correctly on iOS and Web
The field to the hidden/shown appears at the end of the form and not in the position defined in json.

**Minimal Reproduction**
Here is an example form with the issue
```
[

	{
		"type": "label",
		"key": "Heading",
		"templateOptions": {
			"text": "When completing this form Time Spent refers to the duration of the activity rounded to the nearest 15 minute interval. "
		}
	},

	{
		"type": "label",
		"key": "Heading",
		"templateOptions": {
			"text": "Examples:"
		}
	},

	{
		"type": "label",
		"key": "Heading",
		"templateOptions": {
			"text": "- 1 hour and 15 min enter Time Spent as 1.25"
		}
	},
	{
		"type": "label",
		"key": "Heading",
		"templateOptions": {
			"text": "- 1 hour and 30 min, enter Time Spent as 1.5"
		}
	},
	{
		"type": "label",
		"key": "Heading",
		"templateOptions": {
			"text": "- 1 hour and 45 min, enter Time Spent as 1.75"
		}
	},

	{
		"key": "aSupport Date",
		"type": "input",
		"templateOptions": {
			"type": "text",
			"label": "Date:",
			"required": true,
			"placeholder": "DD/MM/YYYY",
			"maxLength": 10
		}
	},
	{

		"key": "bTaskSupport",
		"type": "input",
		"templateOptions": {
			"label": "Task Support:",
			"required": false,
			"defaultvalue": "0",
			"placeholder": "Enter Time Spent Here e.g. 1.5",
			"maxLength": 4
		},
"defaultValue" : "0"
	},

	{
		"key": "cTask Support Description ",
		"type": "textarea",
		"templateOptions": {
			"label": "Task Support Description",
			"required": true,
			"placeholder": "Enter Description Here",
			"rows": 4,
			"maxLength": 1000
		},
		"hideExpression": "!model.bTaskSupport"

	},

	{
		"key": "dPersonalSupport",
		"type": "input",
		"templateOptions": {
			"label": "Personal Support:",
			"required": false,
			"defaultvalue": "0",
			"placeholder": "Enter Time Spent Here e.g. 1.5",
			"maxLength": 4
		}
	},

	{
		"key": "ePersonal Support Description",
		"type": "textarea",
		"templateOptions": {
			"label": "Personal Support Description",
			"required": true,
			"placeholder": "Enter Description Here",
			"rows": 4,
			"maxLength": 1000
		},
		"hideExpression": "!model.dPersonalSupport"
	}
]
```
**Your Environment**

- Angular version: 13.1.2
- Formly version: 6.0.0-next.7
- Nativescript: 8.1.5

**Additional context**

**Comment by jigsawmegs** [comment] 2022-02-01 03:10
This issue did not appear in earlier versions of formly

**Comment by aitboudad** [comment] 2022-02-01 17:02
Its a either a [NativeScript Angular](https://github.com/NativeScript/angular) or [NativeScript](https://github.com/NativeScript/NativeScript) bug.

The render part doesn't seems to be in the correct order compared to the tree element presented in debug tool.
![Screenshot from 2022-02-01 17-26-45](https://user-images.githubusercontent.com/1753742/152010328-678ea70d-0b3a-4e2b-8e91-20cad1f1a4cd.png)
The selected element in debug tool refer to `task support description` field then followed by `Personal Support` which is the opposite of the rendered part.

Hi @NathanWalker, do you have an idea of what could be wrong here? you can check the reproduction example here https://github.com/aitboudad/formly-nativescript-issue3165.

**Comment by jigsawmegs** [comment] 2022-02-17 21:19
Any update from @NathanWalker
I have an app update I can't release

**Comment by aitboudad** [comment] 2022-02-17 21:31
@jigsawmegs you may use the following workaround:

1- Disable `lazyRender`:

```patch
FormlyModule.forRoot({
+ extras: {
+   lazyRender: false,
+ },
}),
```

2- Control field visibility using `ngIf`: https://stackblitz.com/edit/angular-p4xdvv

**Comment by aitboudad** [comment] 2022-02-18 20:28
Closing as it not related to our side

**Closed by aitboudad** 2022-02-18 20:28 UTC
Labels: bug

**Comment by aitboudad** [comment] 2022-02-19 00:03
> If set LazyRender: false the hidden fields always show.

True, in addition you should apply `nativescriptExtension` provided in the above example https://stackblitz.com/edit/angular-p4xdvv

**Comment by jigsawmegs** [comment] 2022-02-19 00:18
If I apply nativescriptExtension  hidden fields end up at the end of the form when shown... so not a work around

**Comment by aitboudad** [comment] 2022-02-19 00:35
try to use `style` to control the field visibility instead of `ngIf` in `NativescriptWrapperComponent`

**Comment by jigsawmegs** [comment] 2022-02-19 05:52
Tried: 
[visibility]="field.hide ? 'collapse' : 'visible'"
[hidden]="field.hide"
[style.display]="field.hide ? 'none' : 'block'"

All give the same result -  on becoming visible they append to the end of the form

**Comment by jigsawmegs** [comment] 2022-02-19 06:44
Formly for Web works fine. Its only Formly on Nativescript that has the issue.

**Comment by aitboudad** [comment] 2022-02-21 20:27
@jigsawmegs visibility is working for me, here is the updated `NativescriptWrapperComponent`:

```ts
@Component({
  selector: 'formly-wrapper-nativescript',
  template: `
  <StackLayout [visibility]="field.hide ? 'collapse' : 'visible'">
    <ng-container #fieldComponent></ng-container>
  </StackLayout>
  `,
})
export class NativescriptWrapperComponent extends FieldWrapper {
}
```

**Comment by jigsawmegs** [comment] 2022-02-21 20:46
Fantastic. It works as expected
Thank you so much for that.

**Comment by jigsawmegs** [comment] 2022-02-23 05:40
In case someone else has this issue, while
<StackLayout [visibility]="field.hide ? 'collapse' : 'visible'">
works for showing/hiding it fails when dealing with required fields that are hidden..
The form won't submit when a required field is hidden in this way.

Use the original option
<StackLayout *ngIf="!field.hide">
And all works as expected

**Comment by aitboudad** [comment] 2022-02-23 10:12
@jigsawmegs it should work, please create a new issue with a reproduction example so I can further check it.
