### ISSUE TITLE
Seeking Recommendation: Compatible  JSON Builder or Designer

### ISSUE THREAD

**Issue by yaronmil** [ngx-formly/ngx-formly#3893] opened 2024-04-15 08:14 UTC
I'm currently on the lookout for a tool or library that seamlessly integrates with Angular and facilitates the generation of JSON structures, ideally tailored to fit ngx-formaly requirements.

**Comment by aitboudad** [comment] 2024-10-13 08:22
Duplicate of #1524

**Closed by aitboudad** 2024-10-13 08:22 UTC
Labels: question
