### ISSUE TITLE
Can we use several formly-form tags to facilitate the positioning of the fields?

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#1416] opened 2019-02-14 15:15 UTC
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I would like to place fields as I want without creating customs type to do it.

You help me with my custom type card and it works perfectly :). But now I want to add buttons and grids like AgGrid between some fields in a tab and it becomes complicated with customs type.

So I would like to have several formly-form to inject the fields I want. When I used Formly 1.x this worked well but when I try this today on Formly 4.x the model isn't correctly managed.

My question is: can I use several formly-form tags?
If not, how I can easily place my fields without creating a bunch of customs type to have the desired behavior?

Example of my current project, something more concrete to understand. I have only one form but I need to add buttons which call other forms. And some data need to be displayed in a grid: 

```
<form [formGroup]="etudeForm" (ngSubmit)="saveEtude(etudeModel)">
  <div class="row mb-3">
    <div class="col">
      <formly-form [form]="etudeForm" [model]="etudeModel" [fields]="etudeFields" [options]="etudeOptions"
                   (modelChange)="etudeModelChange()">
      </formly-form>

      <cometh-card-tabs [className]="'border-danger'" *ngIf="etudeFields && etudeFields.length > 0">
        <cometh-card-tab [tabTitle]="'Etude'">
          <formly-form [form]="etudeForm" [model]="etudeModel" [fields]="etudeFieldsEtude" [options]="etudeOptions"
                       (modelChange)="etudeModelChange()">
          </formly-form>
        </cometh-card-tab>
        <cometh-card-tab [tabTitle]="'Administratif'">
          <formly-form [form]="etudeForm" [model]="etudeModel" [fields]="etudeFieldsAdministratif" [options]="etudeOptions"
                       (modelChange)="etudeModelChange()">
          </formly-form>
        </cometh-card-tab>
        <cometh-card-tab [tabTitle]="'Assurance'">
          <div class="cometh-btn-group">
            <button type="button" class="btn btn-success" (click)="addAttestationAssurance()">Ajouter une attestation d'assurance</button>
            <button *ngIf="showSecondButton" type="button" class="btn btn-success"
                    (click)="addAttestationProlongationAssurance()">Ajouter une attestation de prolongation d'assurance
            </button>
            <button *ngIf="showThirdButton" type="button" class="btn btn-light"
                    (click)="deleteAttestationAssurance()">Supprimer l'attestation d'assurance
            </button>
            <button *ngIf="showFourthButton" type="button" class="btn btn-light"
                    (click)="deleteAttestationProlongationAssurance()">Supprimer l'attestation de prolongation d'assurance
            </button>
          </div>

          <ag-grid-angular *ngIf="rowData.length > 0"
                           #assuranceGrid
                           class="ag-theme-balham mt-3"
                           [domLayout]="domLayout"
                           [rowData]="rowData"
                           [columnDefs]="columnDefs"
                           [defaultColDef]="defaultColDef"
                           [rowClassRules]="rowClassRules"
                           [context]="context"
                           (gridReady)="onGridReady($event)"
                           (rowDataChanged)="onRowDataChanged($event)"
                           (rowSelected)="onRowSelected($event)">
          </ag-grid-angular>
        </cometh-card-tab>
      </cometh-card-tabs>

      <formly-form [form]="etudeForm" [model]="etudeModel" [fields]="etudeFieldsOther" [options]="etudeOptions"
                   (modelChange)="etudeModelChange()">
      </formly-form>

      <div class="cometh-btn-group float-right">
        <button type="submit" class="btn btn-primary">submit</button>
      </div>
    </div>
  </div>
</form>
```

**Expected behavior**
Possibility to place fields where I want.
Possibility to add other components between fields like button, grid, todo list, etc...

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/github/Jukien/Formly-Sandbox

* **Angular version:** 7.2.4  

* **Formly version:** 4.8.2

* **Browser:** 
Chrome 71.0.3578.98

* **Language:** 
TypeScript 3.2.4

**Comment by aitboudad** [comment] 2019-02-14 15:42
not sure I clearly understood, could you please confirm that the following issue https://github.com/ngx-formly/ngx-formly/issues/1405 is similar to what you're asking for?
Thanks!

**Comment by Jukien** [comment] 2019-02-14 16:12
Hi @aitboudad , that right. It's exactly what I'm looking for :)
Do you know if this feature will be developed?
Thank you!

**Comment by aitboudad** [comment] 2019-02-14 16:17
> Do you know if this feature will be developed?

I think so :)

**Comment by aitboudad** [comment] 2019-02-14 23:43
duplicate of #1405 

**Note**: don't expect that will be landed anytime soon, probably in `V6` but not sure yet.

**Closed by aitboudad** 2019-02-14 23:43 UTC

**Comment by Jukien** [comment] 2019-02-15 11:56
@aitboudad I tried with the **5.0.0-rc.0** version and it fixed the issue!
The model is now well injected.
I'm still testing but so far we can use multiple formly-form tags without problem.
Just great :)

P.S. : I updated the [demo on Stackblitz](https://stackblitz.com/github/Jukien/Formly-Sandbox)
