### ISSUE TITLE
I need to listen to the next and previous button click in stepper form, how can I do that with current example available on ngx-formly site?

### ISSUE THREAD

**Issue by anushreenk** [ngx-formly/ngx-formly#2695] opened 2021-02-05 11:34 UTC
I am implementing steeper form, I need to listen to onclick eevent of next and previous button how can I achive that?

**Comment by aitboudad** [comment] 2021-02-09 07:25
duplicate of #2698

**Closed by aitboudad** 2021-02-09 07:25 UTC
Labels: question

**Comment by anushreenk** [comment] 2021-02-10 13:53
Thanks for solution, I will try and get it work.
