### ISSUE TITLE
Deleting fields that are displayed in Mat-Table causing other fields to delete

### ISSUE THREAD

**Issue by johnRambo2k14** [ngx-formly/ngx-formly#2065] opened 2020-01-30 18:32 UTC
**Description**
I have displayed my ArrayType component using material table, currently when i delete multiple rows other rows delete randomly. 

I'm not sure why this happens but here are the reproduction steps you can do in stackblitz:

**Minimal Reproduction**
 - click add 3 times
 - delete all new 3 rows
 - observe the existing and last row with id of "This row dies :(", this value is removed.
 - Note: the console will log what row will be deleted, this is reflective on the model index.

https://stackblitz.com/edit/ngx-formly-ui-material-rj4l6p

**Your Environment**

- Angular version: ~8.2.13
- Formly version: 5.5.10

I have noticed another similar issue, which i think could be the same problem: #2045

**Comment by aitboudad** [comment] 2020-02-03 15:29
This issue has been fixed and released as part of [v5.5.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by johnRambo2k14** [comment] 2020-02-04 10:04
@aitboudad The issue still persists if I updated to 5.5.11:

Steps to reproduce:

- Add 3 rows
- Remove 3 rows
- See last row is removed randomly

https://stackblitz.com/edit/ngx-formly-ui-material-z65mew

**Comment by aitboudad** [comment] 2020-02-04 11:05
> See last row is removed randomly

I'm not able to reproduce it but I've noticed another issue where where the newly added rows share the same value after removing 3 rows.

**Comment by johnRambo2k14** [comment] 2020-02-04 11:32
Yeah its strange, I get different results, i'm not sure if this a material problem 🤔

**Comment by aitboudad** [comment] 2020-02-05 11:31
probably an issue in Formly 😄

**Comment by FritzHerbers** [comment] 2020-02-05 12:26
@aitboudad 
Can you please tell the reproduction steps for the "added rows share the same value" problem.
The problem exists on this https://stackblitz.com/edit/ngx-formly-ui-material-z65mew ?

**Comment by aitboudad** [comment] 2020-02-05 12:49
@johnRambo2k14 if the model root is an array you should pass a `FormArray` instance instead of `FormGroup`.

```ts
this.form = new FormArray([]);
```

@FritzHerbers when passing a `FormGroup` for Array type the created field use the existing FormControl (`FormArray` reorder the controls on insert/remove at a certain position which is not the case of `FormGroup`).

**Closed by aitboudad** 2020-02-05 12:49 UTC
Labels: bug
