### ISSUE TITLE
Disable the form on NgOnInit doesn't disable formly

### ISSUE THREAD

**Issue by luizfbicalho** [ngx-formly/ngx-formly#2598] opened 2020-11-26 23:56 UTC
**Description**

```ts
export class AppComponent  implements OnInit{
  form = new FormGroup({});
  
  ngOnInit(){
    this.form.disable();
  }
```

**Minimal Reproduction**
If on init I disable the form, it doesn't work the disable.

https://stackblitz.com/edit/angular-fpuvb7

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.6

**Additional context**

**Comment by SubrahmanyaV** [comment] 2020-12-03 12:15
1. Am facing the same problem with Angular version 10.1 & Formly Material 5.10.3
2. In my style sheet, I have the following;
**.disabled,
[disabled] {
    color: mediumblue;
}**
This has no effect on the fields disabled in Formly using **_field_.templateOptions.disabled= true;**

**Comment by luizfbicalho** [comment] 2020-12-04 14:01
There was another issue that @aitboudad  recomended the this.form.disable(); to disable the form.
do we need to use it in another way to disable on init?

**Comment by SubrahmanyaV** [comment] 2020-12-06 11:31
Does this fix address the issue with the styling also ... here's the issue I had noticed earlier;
In my style sheet, I have the following;
**.disabled,
[disabled] {
color: mediumblue;
}**
This has no effect on the fields disabled in Formly using field.templateOptions.disabled= true;

**Comment by aitboudad** [comment] 2020-12-06 12:14
@SubrahmanyaV there is no issue in styling, just make sure the defined `[disabled]` style is not overridden by the existing style.

**Comment by SubrahmanyaV** [comment] 2020-12-07 08:16
> @SubrahmanyaV there is no issue in styling, just make sure the defined `[disabled]` style is not overridden by the existing style.

I have checked for style override, there is none... However the following style spec'ed in my .scss file 'does not work' (even when I spec 'important' against the style attribute);
**.disabled,
[disabled] {
    color: mediumblue !important;
}**

Not sure if this info helps but I have two forms on the same page, one is an Angular Material 10 form & the second is the Formly/Material form.  The color style is reflected in Angular form but not in Formly form.

Below is the snippet of code I am using to disable the Formly fields;
        **// --- Disable Document entry fields
        this.documentFields.forEach(docField => {
          docField.templateOptions.disabled = true;
        });**

Background: I fetch my Formly field definition from the database & subsequently disable all the fields with above code. 

![Disable style issue](https://user-images.githubusercontent.com/43541702/101325866-74bf3200-3892-11eb-8eac-3bddd9f4e5ed.png)

**Comment by aitboudad** [comment] 2020-12-07 08:23
@SubrahmanyaV could you please provide a simple reproduction example using our stackblitz https://stackblitz.com/edit/ngx-formly-ui-material

**Comment by aitboudad** [comment] 2020-12-08 14:43
This issue has been fixed and released as part of [v5.10.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by SubrahmanyaV** [comment] 2020-12-09 14:57
- I upgraded to v5.10.7 before testing this.
- The styling is still 'not working'.  
- Description of the problem is exactly as I had narrated earlier.
Looking forward to a resolution ...

**Comment by luizfbicalho** [comment] 2020-12-09 17:16
I got the inverse problem now @aitboudad 
Let me put some steps
1) I open the edit page, it shows me the form enabled
2) i close and open the details page, the form opens disabled
3) i close and open the edit again, the form opens disabled, but if I print the enabled property od the form, it's true


Seems to me that there is some cache from the previous component in the memory, it's strange, I have another issue when I change the item i'm editing, but I'll try to reproduce better

**Comment by aitboudad** [comment] 2020-12-09 18:05
A reproduction is needed 🙏!

**Comment by luizfbicalho** [comment] 2020-12-09 18:09
is it ok if I zip an example and attach it here?

**Comment by aitboudad** [comment] 2020-12-09 18:12
ok

**Comment by luizfbicalho** [comment] 2020-12-09 18:41
[example.zip](https://github.com/ngx-formly/ngx-formly/files/5667906/example.zip)

To execute this you need this steps

1) npm install
2) run
3) go to url /complexidade
4) open one item on the grid with the pencil
5) open the same item with the eye
6) open the same item with the pencil (this will open disabled, but the Form is enabled)

On the side I have another issue, if you open one item, and you open another item, you will get an error from the kendo editor, I opened an issue in kendo but I coudn't solve it, they claim it's something about formly
I think it's related with this "cache" from last component

**Comment by luizfbicalho** [comment] 2020-12-10 19:14
This means that you sucessfully ran the code I sent?

did you catch the two errors ? the disables one and the html editor one? I put them together because seems to be the same origin.

**Comment by aitboudad** [comment] 2020-12-10 20:53
I'm not able to make it work due to the missing of `@ngx-formly/agl-kendo` package, I think its better to provide me a simple reproduction using stackblitz https://stackblitz.com/edit/ngx-formly-ui-bootstrap

For the editor error, probably the editor component doesn't support reactive-form, the solution is to rely on editor outputs to trigger formControl value changes:

```
<kendo-editor (onChange)="formControl.setValue($event)" ...></kendo-editor>
```

Note: `onChange` here is just an example, you may check the kendo doc to get the output name

**Comment by luizfbicalho** [comment] 2020-12-10 21:04
the AGL-kendo is on the zip file

the editor I opened an issue on kendo and it's ok for reactive forms

**Comment by aitboudad** [comment] 2020-12-10 21:25
still getting some errors, a simple reproduction using https://stackblitz.com/edit/ngx-formly-ui-bootstrap is needed :pray:

**Comment by luizfbicalho** [comment] 2020-12-10 21:42
I put the code on https://stackblitz.com/edit/angular-ivy-q3icdx?file=package.json 
but for some reason it's not running there, I'm adding another zip here, or you can download the project from stackblitz

[prject.zip](https://github.com/ngx-formly/ngx-formly/files/5675767/prject.zip)

**Comment by aitboudad** [comment] 2020-12-10 22:20
sorry but that took me much more time than I expected, feel free to reopen when you can provide a small reproduction example using stackblitz.com

**Comment by luizfbicalho** [comment] 2020-12-11 00:13
@aitboudad I made it work, it's taking me much more time than I expected also

https://angular-ivy-q3icdx.stackblitz.io/#/complexidade

the css style is not working but you can see the problem

there are 3 different problems 

1) id you edit one line and then edit another line, the kendo html editor shows an error
2) if you edit, then display the same line  now it's making an error, on the third time it shows correctly the display
3) after error 2, if you came back to edit, it's only in display mode, doesn't came back to edit

https://stackblitz.com/edit/angular-ivy-q3icdx?file=package.json

Thanks for the help

**Comment by aitboudad** [comment] 2020-12-11 06:18
The shared `stackblitz` is not working, contains two files only, make sure you've saved you work there

**Comment by luizfbicalho** [comment] 2020-12-11 14:19
I tried to upload to stackblitz, it didn't work
I put it on github and sync  to stackblitz but it doesnt save

the code is in this repo

https://github.com/luizfbicalho/angular-ivy-q3icdx/tree/master
I'll try to make stackblitz work later, but you can see it in this repo

**Comment by luizfbicalho** [comment] 2020-12-12 15:23
Now it's working on stackblitz @aitboudad 

https://stackblitz.com/edit/angular-ivy-fnrshf?file=src%2Fapp%2Fshared%2Ferror.handler.ts


https://angular-ivy-fnrshf.stackblitz.io/#/complexidade

**Comment by aitboudad** [comment] 2020-12-13 10:45
`Side note`: when I'm asking for a minimal reproduction example, it doesn't mean you've to put your entire codebase as its time consuming for both of us.

**Comment by luizfbicalho** [comment] 2020-12-13 22:18
Sorry but i couldn't reproduce It the other way

**Comment by aitboudad** [comment] 2020-12-14 20:37
I've reverted the initial commit which attempts to take account of form disabled state during the build step, so instead of that the solution is to disable the form using hooks https://github.com/ngx-formly/ngx-formly/issues/2379#issuecomment-662957459

**Closed by aitboudad** 2020-12-14 20:37 UTC
Labels: bug

**Comment by luizfbicalho** [comment] 2020-12-14 22:19
I changed to this and got this error


TypeError: Cannot set property model of [object Object] which has only a getter
    at FormlyForm.ngOnChanges (ngx-formly-core.js:1132)
    at FormlyForm.rememberChangeHistoryAndInvokeOnChangesHook (core.js:4542)
    at callHook (core.js:4780)
    at callHooks (core.js:4746)
    at executeInitAndCheckHooks (core.js:4698)
    at refreshView (core.js:9153)
    at refreshComponent (core.js:10291)
    at refreshChildComponents (core.js:8935)
    at refreshView (core.js:9188)
    at refreshEmbeddedViews (core.js:10245)

I'll update the stackblitz today

**Comment by luizfbicalho** [comment] 2020-12-14 22:46
I found the reason @aitboudad 

there is something about reading the JSON and loading the fields from it
if I use the SetFields = () => fieldsJson.fields 
I get some errors
if I copy the json on the source as a typescript variable, it works, do you have any idea what can do that?

**Comment by aitboudad** [comment] 2020-12-16 10:38
use `immutable`, if you don't want that behavior:

```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { immutable: true }
    }),
  ],
})
```

Also to track the model value changes, use `modelChange` output:
```html
<formly-form [model]="model" (modelChange)="modelChange($event)"` ...>
```

**Comment by luizfbicalho** [comment] 2020-12-16 12:14
Thanks, this looks nice, I have three questions

1) Is there a pro/con to use this immutable?
2) Is there an example with all those extras?
3) why do I nees to track the modelChange? with immutable it looses the reactive?

**Comment by aitboudad** [comment] 2021-01-02 20:21
> 1) Is there a pro/con to use this immutable?
> 3) why do I need to track the modelChange? with immutable it looses the reactive?

We try to not touch `formly-form` inputs and instead rely on `formly-form` outputs to get notified of changes, still experimental but we may use some parts of it as default in the future.

> 2) Is there an example with all those extras?

Check the source code https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/models/config.ts#L55-L82

**Comment by SubrahmanyaV** [comment] 2021-01-03 14:21
> * I upgraded to v5.10.7 before testing this.
> * The styling is still 'not working'.
> * Description of the problem is exactly as I had narrated earlier.
>   Looking forward to a resolution ...

Do you have an update on the styling issue, please let me know the version if it has been addressed, thanks.

**Comment by aitboudad** [comment] 2021-01-03 15:41
@SubrahmanyaV could you please put a little effort to provide a reproduction (https://stackblitz.com/edit/ngx-formly-ui-material), it essential for me in order to gain some time, and thanks in advance for your understanding!

**Comment by boring91** [comment] 2024-06-17 06:05
@aitboudad I am having the same issue here (reproduction: https://stackblitz.com/edit/ngx-formly-ui-material-yzv8g9?file=src%2Fapp%2Fapp.component.ts). In the code you can see at line 67 I'm disabling the form through the form group but it does not work. When I try to disable the form after some time it does work (see the commented lines 69 - 71). Hope it helps.

**Comment by FritzHerbers** [comment] 2024-06-17 07:09
@boring91 
At the moment of constructor creation, no Angular code has been run, the view is not rendered. 
You have to await the rendering:
```
import { Component, AfterViewInit  } from '@angular/core';
....
export class AppComponent implements AfterViewInit {
....
  ngAfterViewInit() {
    this.form.disable();
  }
```

**Comment by boring91** [comment] 2024-06-17 07:16
@FritzHerbers Thanks that helped. I have another issue (updated the sample code). If I try to change the fields array, the form does not retain its disabled state.

**Comment by FritzHerbers** [comment] 2024-06-17 10:00
`this.form.disable()` disables the rendered fields once, but does not retain the forms disabled state for future(added/changed) fields.
What you are looking for is something like `this.form.disabled()` which would retain the forms disabled state (I am unsure if there is such a method).

Change your code to the following:
```
  ngAfterViewInit() {
    this.form.disable();

    setTimeout(() => {
      this.fields = [
        {
          key: 'input',
          type: 'input',
          props: {
            label: 'Input',
            placeholder: 'Input placeholder',
            required: false,
          },
        },
      ];
      
      // disable at the next tick
      setTimeout(() => {
        this.form.disable();
      }, 0);
      
    }, 2000);

  }```
