### ISSUE TITLE
Add support Ionic v8

### ISSUE THREAD

**Issue by studentrk** [ngx-formly/ngx-formly#3919] opened 2024-05-19 18:25 UTC
When installing @ngx-formly/ionic it says that it does support only up to @ionic/angular^7.0.0.

**Question**
Do you know if it could break the forms when using --legacy-peer-deps with ionic/angular 8.1.2?

Thank you for updating it so it does support @ionic/angular^7.0.0.

**Comment by FloppyNotFound** [comment] 2024-05-30 08:35
Duplicate of #3902

**Closed** 2024-05-30 16:19 UTC
Labels: enhancement
