### ISSUE TITLE
Error: Cannot read properties of undefined (reading '_fields') in unregisterControl function since version 6.1.1

### ISSUE THREAD

**Issue by yoannlepetit** [ngx-formly/ngx-formly#3810] opened 2023-11-07 17:19 UTC
Hello,
First, thank for this lib. It is very useful.

**Description**
Since version 6.1.1, I cannot use FieldArrayType with no key. It was OK before 6.1.1 (for example 6.1.0 and 6.0.2).
I have this error 

```
ERROR
Error: Cannot read properties of undefined (reading '_fields')
```

I do some research and it seems to be the commit f1add094250af2b0f179b7a13c0d10a16fd0928b in the file src/core/src/lib/templates/field-array.type.ts.

You have change the check of the model length.
```
- const length = field.model ? field.model.length : 0; // return undefined if no key in field
+ const length = Array.isArray(field.model) ? field.model.length : 0; // return 0 if no key
```
Fix is very good and must stay like this. 
But, the side effect, the code after is being executed.

```
if (field.fieldGroup.length > length) {
      for (let i = field.fieldGroup.length - 1; i >= length; --i) {
        unregisterControl(field.fieldGroup[i], true);
        field.fieldGroup.splice(i, 1);
      }
}
```
BUT there is no `formControl` to unregister and the `unregisterControl` function do not check if a `formControl` exists on a `field`.

```
export function unregisterControl(field: FormlyFieldConfigCache, emitEvent = false) {
  const control = field.formControl; // formControl is undefined
  const fieldIndex = control._fields ? control._fields.indexOf(field) : -1; // here the error occurs. Should control be check??
  if (fieldIndex !== -1) {
    control._fields.splice(fieldIndex, 1);
  }
```
Should the `formControl` be check if `undefined`? I didn't try but that should be good for my case but can cause side effect again.

A better solution should be to check if a field have a key or not. 
In case there is no key, then skip it to create/unregister `formControl`. I don't know if it is possible.
In case there is a key, then keep the actual process.

Let me know your taught.

**Minimal Reproduction**
There is a formly FieldArrayType tabs.type.ts that uses tabset of ngx-bootstrap to display tab.
The application is forked from your project with bootstrap.
The form is just 2 tab with 1 input each.
With first version, nothing is displayed and an error occurs in the console.
With the second version, display is ok and everything is workiing.

First version reproduction with version 6.1.1 not working:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-heakr1

Second version reproduction with version 6.1.0 working
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-hme5ha

**Your Environment**

- Angular version: 16.0.0 (but not mater for this bug)
- Formly version: >=6.1.1

Best regards.

Yoann Le Petit

**Comment by shprink** [comment] 2023-12-05 08:57
Thanks a lot @yoannlepetit I had the same issue and fixing my dependencies to 6.1.0 did the trick.

    "@ngx-formly/core": "6.1.0",
    "@ngx-formly/ionic": "6.1.0",
    
I hope this can be fixed in coming releases

**Comment by yoannlepetit** [comment] 2023-12-05 09:41
Good to hear @shprink !
I don't think this issue will be fixed soon, I didn't have any reply to this issue yet.
We just have to wait 🙂.

**Comment by aitboudad** [comment] 2023-12-10 11:08
Hi, the example doesn't provide a clear idea of the issue (do you expect the tab field to be an array and object), could you please elaborate about your use case?

**Comment by yoannlepetit** [comment] 2024-01-09 15:07
Hi @aitboudad, thanks to respond.
I think I expect the tab field to be just a field without both model and AbstractControl because there is no key. 
What do you think about that? Is it possible?

**Comment by yoannlepetit** [comment] 2024-05-29 14:29
Hi, is there any update?

**Comment by aitboudad** [comment] 2024-05-29 22:15
hi, I'll check it next week.

**Comment by aitboudad** [comment] 2024-06-01 07:17
> A better solution should be to check if a field have a key or not.
In case there is no key, then skip it to create/unregister formControl. I don't know if it is possible.
In case there is a key, then keep the actual process.


@yoannlepetit in your case, do you use`fieldArray` to the `tabs` field ?
if not I think we can add a check to skip that part by checking the if `fieldArray` is passed or not.

**Comment by aitboudad** [comment] 2024-06-01 07:25
I found another better way, just override `FieldArrayType::onPopulate`:

```patch
export class TabsTypeComponent
  extends FieldArrayType<FieldArrayTypeConfig<TabsProps>>
  implements FormlyExtension, OnInit
{
+  override onPopulate(): void {}
}
```

**Closed by aitboudad** 2024-06-01 07:25 UTC
Labels: bug

**Comment by yoannlepetit** [comment] 2024-06-04 07:20
@aitboudad It seems to work on stackblitz. 
Thanks a lot.

**Comment by shprink** [comment] 2024-06-04 13:44
I am running 6.3.3 and still have the issue

**Comment by yoannlepetit** [comment] 2024-06-04 13:48
@shprink 
I changed version of ngx-formly to 6.3.3 and it works for my case. Look here: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-arl3op
 
I did not changed version in my current project, I need time for that.

**Comment by shprink** [comment] 2024-06-05 07:53
your link has still 6.1.1 installed even if it has 6.3.3 in the package.json.

if I install the updates I get that

![image](https://github.com/ngx-formly/ngx-formly/assets/1388706/392fa788-2de4-432f-96e9-41f4f6178f2b)

**Comment by aitboudad** [comment] 2024-06-05 08:21
@shprink no need to update Formly version, please check my comment https://github.com/ngx-formly/ngx-formly/issues/3810#issuecomment-2143340414

**Comment by shprink** [comment] 2024-06-05 09:44
@aitboudad your "hack" works with 6.3.3 I can confirm. But it is not a fix IMO

**Comment by aitboudad** [comment] 2024-06-05 09:59
@shprink its a fix, because your needs is not what array type supposed to provide unless I didn't understood the use case which I've asked above https://github.com/ngx-formly/ngx-formly/issues/3810#issuecomment-1848932588

**Comment by shprink** [comment] 2024-06-07 14:32
Here is my need, it is a group with a repeat section:

without your "hack/fix" I have the error. What am I doing wrong here ?

```
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FieldArrayType } from '@ngx-formly/core';

@Component({
  selector: 'formly-item-group',
  template: `
    <ion-item-group>
      <ion-item-divider
        *ngIf="field.props?.label"
        [color]="field.props['color']"
      >
        <ion-label>{{ field.props.label }}</ion-label>
      </ion-item-divider>

      <ion-item *ngIf="field.props?.description">
        <ion-label class="ion-text-wrap">
          {{ field.props.description }}
        </ion-label>
      </ion-item>

      <formly-field
        [field]="field"
        *ngFor="let field of field.fieldGroup; let i = index"
      ></formly-field>
    </ion-item-group>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FormlyItemGroup extends FieldArrayType {
  override onPopulate(): void {}
}

```

**Comment by rajanchavda06** [comment] 2025-04-11 19:59
Still facing this issue in **v6.3.12** @aitboudad. I tried your solution, but not working. 
Any more update on this?
