### ISSUE TITLE
Change method on templateOptions not working anymore on checkbox

### ISSUE THREAD

**Issue by bjarne-callewaert** [ngx-formly/ngx-formly#2353] opened 2020-07-09 14:51 UTC
**Description**
We sometimes use the change function on a checkbox to set other fields. However on the latest version it is not working anymore

**Minimal Reproduction**
see: https://stackblitz.com/edit/ngx-formly-ui-material-zsnjs9

On a select, it is still working, however changing the checkbox does not trigger the change function anymore.

**Your Environment**

- Angular version: 9.2.11
- Formly version: 5.8.0

**Comment by aitboudad** [comment] 2020-07-14 12:35
This issue has been fixed and released as part of [v5.9.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by bjarne-callewaert** [comment] 2020-07-15 06:30
Hi, thanks for the quick response. Seems to be working well again!
Is it possible to also add the change event back on the material toggle type?

**Comment by aitboudad** [comment] 2020-07-20 14:24
change event for toggle type is fixed in  [v5.9.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.1)

**Comment by galearemus** [comment] 2022-02-17 11:17
@aitboudad  I think this is reproducing again in the latest formly version (5.10.31) with angular 13 (13.2.0)

**Closed** 2022-02-22 12:30 UTC
Labels: bug

**Comment by hhetland** [comment] 2022-02-22 12:36
FYI: I noticed the same thing on the latest build on v.6 last week.
Reverted back to 5 since I believed it was my code, but it might be a related issue?

**Comment by aitboudad** [comment] 2022-02-22 12:40
Probably not related, the change that produced that regression isn't applied to `v6` yet.
