### ISSUE TITLE
i want display today date displaying inside form filed default?

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#3048] opened 2021-11-11 12:48 UTC
{
      key: 'todayDate',
      type: 'input',
      defaultValue: new Date(),
      templateOptions: {
        label: 'Today Date',
        type:'date'
      },
    },
![Screenshot (182)](https://user-images.githubusercontent.com/67161080/141300613-62e80405-3a11-436c-b718-01ea2e2f6313.png)

**Comment by Preethi-Guna** [comment] 2021-11-16 10:44
Hi @vardhan1122,
you can use expressionProperties for assigning values to the model directly. Like,
{
    key: 'todayDate',
    type: 'input',
    templateOptions: {
    label: 'Today Date',
    type:'date'
   },
  "expressionProperties":
        {
          "model.todayDate": "new Date()"
        }
}..
Hope this helps!!!!!

**Comment by vardhan1122** [comment] 2021-11-16 12:36
Thank you for response, but i want showing default date inside input date
form filed,[image: Screenshot (190).png]

**Comment by vardhan1122** [comment] 2021-11-16 16:51
Hi Ngx-Formly/Ngx-Formly,
Please guide me this topic, please...

**Comment by aitboudad** [comment] 2021-11-20 21:34
duplicate of https://github.com/ngx-formly/ngx-formly/issues/3058

**Closed by aitboudad** 2021-11-20 21:34 UTC
Labels: question
