### ISSUE TITLE
Support for CSP unsafe-eval while using expressions in JSON powered schema

### ISSUE THREAD

**Issue by Arunkumar81292** [ngx-formly/ngx-formly#3986] opened 2024-09-11 10:48 UTC
**Question**

Need Support for CSP unsafe-eval while using expressions in JSON powered schema
we used ngx-formly version of 6.3.0
Sample JSON
{
            "key": "firstName",
            "type": "input",
            "props": {
              "label": "First Name",
              "maxLength": 30,
              "required": true
            },
            "expressions": {
              "hide": "!formState.permissions.lastName",
              "props.disabled": "formState.readonly"
            }
We push dynamic forms from backend as JSON schema and manage to load it in UI.
After implementing the CSP script: 'self' we got the unsafe-eval in formly library and I found that using expressions in JSON powered schema would cause CSP unsafe eval issue.
![image](https://github.com/user-attachments/assets/33b8a543-89f3-43be-a57f-0b57f0b7a24d)

For this scenario, how can we manage our control's disabled or hide state in JSON using model properties or form state.
Also what's the solution in case we need to use expressions especially for the JSON powered schema

**Comment by aitboudad** [comment] 2024-10-13 07:07
Duplicate of #2537

**Closed by aitboudad** 2024-10-13 07:07 UTC
Labels: question

**Comment by lelanLi** [comment] 2024-10-29 02:08
@aitboudad Is there any plan to fix this?
